### ISSUE TITLE
Send email

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/cochair_resources#1]
@strubell : Hey, could you take a quick look at the template and let me know know what you think? If you think it's okay, can you clone this repo, edit this line:

https://github.com/CSWomenUMass/cochair_resources/blob/master/sanitary_products/extract.py#L22

and run the script to send it? It should be super easy. I just want someone who isn't me to do it. Thanks!

**Comment by strubell** [comment]
The template looks great, so if i just change the line to be the commented thing rather than our emails it should be good?

**Comment by strubell** [comment]
K, done. Sweet script, thanks!
